---
- name: Clone Prezto
  git: >
    repo=https://github.com/sorin-ionescu/prezto.git
    dest=~/.prezto
    force=no
  tags: update

- name: Link runcoms
  file: src={{ item }} dest=~/.{{ item | basename }} state=link
  with_items:
    - ~/.prezto/runcoms/zlogin
    - ~/.prezto/runcoms/zlogout
    - ~/.prezto/runcoms/zprofile
    - ~/.prezto/runcoms/zshenv
    - ~/.prezto/runcoms/zshrc

#- name: Install prezto
#  script: install_prezto.sh creates="{{ '~/.zprezto' | expanduser}}"

- name: Link zpreztorc file
  file:
    src: "{{ dotfiles_home }}/roles/zsh/files/zpreztorc.link"
    dest: "{{ '~/.zpreztorc' | expanduser }}"
    state: link

- name: Link zshrc file
  file:
    src: "{{ dotfiles_home }}/roles/zsh/files/zshrc.link"
    dest: "{{ '~/.zshrc' | expanduser }}"
    state: link