
---
- import_tasks: arch.yaml
  when: ansible_os_family == "ArchLinux"
- import_tasks: debian.yaml
  when: ansible_os_family == "Debian"
- import_tasks: mac.yaml
  when: ansible_os_family == "Darwin"

- name: Create ~/.gnupg
  file: >-
    dest=~/.gnupg
    state=directory
- name: Link files
  file: >-
    src={{ item }}
    dest=~/.gnupg/{{ item | basename }}
    state=link
  with_fileglob:
    - ./*